# Generated by Django 6.0.8 on 2026-09-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
